#!/bin/bash
# usage
cmdname="$(basename "$0")"
function usage()
{
    cat <<EOF
Usage:
    $cmdname [command] [args]

Command:
    ssh [user@]<hostname> [-p|--path <path>]                                     adding ssh keys to authorized_keys on remote host
    github <user> [-l|--label <label>] [-p|--path <path>]                        adding ssh keys to github
    bitbucket <user> [-l|--label <label>] [-p|--path <path>]                     adding ssh keys to bitbucket
    gitlab <user> [-l|--label <label>] [-p|--path <path>] [-u|--url <baseurl>]   adding ssh keys to gitlab
EOF
}


curl="curl -s -w \n%{http_code}"
command="$1"
shift
host="$1"
user="$1"
shift

key_path=~/.ssh/id_rsa.pub

label="$(hostname)"
baseurl=""

while (( $# > 0 ))
do
    case "$1" in
        '-l'|'--label')
            label="$2"
            shift 2
            ;;
        '-p'|'--path')
            key_path="$2"
            shift 2
            ;;
        '-u'|'--url')
            baseurl="$2"
            shift 2
            ;;
    esac
done

key_data="$(cat $key_path)"

case "$command" in
    ssh)
        cat <"$key_path" | ssh "$host" "cat >> ~/.ssh/authorized_keys"
        exit $?
        ;;

    github)
        res="$(
        $curl -u "$user" \
            --data "{\"title\":\"$label\",\"key\":\"$key_data\"}" \
            https://api.github.com/user/keys
        )"
        ;;

    bitbucket)
        res="$(
        $curl -u "$user" \
            --data-urlencode "label=$label" --data-urlencode "key=$key_data" \
            https://bitbucket.org/api/1.0/users/"$user"/ssh-keys
        )"
        ;;

    gitlab)
        read -sp "Password: " pass
        echo ""

        if [ -z $baseurl ]; then
            echo "URL is not specified"
            exit 1
        fi

        if ! grep "^https\?://" <<<"$baseurl" 2>&1 > /dev/null; then
            baseurl="https://$baseurl"
        fi
        token="$($curl -k $baseurl/api/v3/session --data-urlencode "login=$user" --data-urlencode "password=$pass" | \
            awk -F',' '/"private_token"/{print $NF}' | awk -F':' '{print $2}' | sed s/[^0-9a-zA-Z]//g)"
        res="$(
        $curl -k --header "PRIVATE-TOKEN: $token" "$baseurl/api/v3/user/keys" \
            --data-urlencode "title=$label" --data-urlencode "key=$key_data"
        )"
        ;;

    *)
        usage
        exit 1
        ;;
esac

status="$(tail -n 1 <<<"$res")"

if grep "^2..$" <<<"$status" 2>&1 > /dev/null; then
    echo "success"
    exit 0
else
    echo "error"
    echo "$res"
    exit 1
fi
