#!/bin/bash
# usage
cmdname="$(basename "$0")"
function usage()
{
    cat <<EOF
Usage:
    $cmdname [command] [args]

Command:
    ssh [user@]hostname       adding ssh keys to authorized_keys on remote host
    github user [label]       adding ssh keys to github
    bitbucket user [label]    adding ssh keys to bitbucket
    help                      print this
EOF
}

key_path=~/.ssh/id_rsa.pub
key_data="$(cat $key_path)"
host="$2"
user="$2"
label="${3:-$(hostname)}"

case "$1" in
    ssh)
        cat <"$key_path" | ssh "$host" "cat >> ~/.ssh/authorized_keys"
        ;;

    github)
        curl -u "$user" \
            --data "{\"title\":\"$label\",\"key\":\"$key_data\"}" \
            https://api.github.com/user/keys
        ;;

    bitbucket)
        curl -u "$user" \
            --data "label=$label" --data-urlencode "key=$key_data" \
            https://bitbucket.org/api/1.0/users/"$user"/ssh-keys
        ;;

    *)
        usage
        exit 1
        ;;
esac
